### ISSUE TITLE
gpg some error.

### ISSUE THREAD

**Issue by acald3ron** [linode/cli#47] opened 2016-12-16 16:29 UTC
I follow the instructions from the website:     https://www.linode.com/docs/platform/linode-cli 
for ubuntu/debian

i got this error:

~$ sudo apt-get update
Get:1 http://mirrors.linode.com/debian testing InRelease [175 kB]
Hit:2 http://security.debian.org/debian-security testing/updates InRelease
Get:3 http://apt.linode.com stable InRelease [3,223 B]                    
Ign:3 http://apt.linode.com stable InRelease             
Get:4 http://apt.linode.com stable/main i386 Packages [759 B]
Fetched 179 kB in 2s (84.4 kB/s) 
Reading package lists... Done
W: GPG error: http://apt.linode.com stable InRelease: The following signatures were invalid: D12F8D2C47B4A16917C9A040BED67E64325A043E
W: The repository 'http://apt.linode.com stable InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by jamesottinger** [comment] 2016-12-19 12:53
Thank you for reporting. I'm unable to reproduce the error. Can you tell me which OS and version you are using?

**Comment by acald3ron** [comment] 2016-12-19 21:15
Debian testing (stretch 9)

**Comment by jamesottinger** [comment] 2016-12-20 20:35
Hum. 🤔 I am still unable to reproduce the issue. I tried Debian 8, Debian 8 upgraded to Stretch, and Debian 8 upgraded to Testing. Can you try removing the key and then adding it again?

**Comment by jamesottinger** [comment] 2016-12-21 13:20
I was able to duplicate with a straight Stretch install. I'll provide and update shortly.

**Comment by jamesottinger** [comment] 2016-12-21 20:40
Our signing level has been increased and we have updated our "stretch" repository.

If you edit /etc/apt/sources.list.d/linode.list and change "stable" to "stretch", you should be good-to-go. Let me know how you make out.

**Comment by acald3ron** [comment] 2016-12-23 16:31
thanks, its fix.

Get:1 http://mirrors.linode.com/debian testing InRelease [175 kB]
Hit:2 http://security.debian.org/debian-security testing/updates InRelease
Hit:3 http://apt.linode.com stretch InRelease                                      
Fetched 175 kB in 1s (96.7 kB/s)                                                   
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by jamesottinger** [comment] 2016-12-23 22:32
Great to hear! Thank you @acald3ron.

I'll close this issue as resolved.

**Closed by jamesottinger** 2016-12-23 22:32 UTC
